/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TtsRouteImport } from './routes/tts'
import { Route as SoftwareCenterRouteImport } from './routes/software-center'
import { Route as SetupWizardRouteImport } from './routes/setup-wizard'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RedeemRouteImport } from './routes/redeem'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LinkRouteImport } from './routes/link'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as KeysRouteImport } from './routes/keys'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DevConfigRouteImport } from './routes/dev-config'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsStarOfficeUiRouteImport } from './routes/labs.star-office-ui'
import { Route as LabsOllamaQwen35RouteImport } from './routes/labs.ollama-qwen35'
import { Route as LabsCompanionRouteImport } from './routes/labs.companion'
import { Route as CompanionFloatingRouteImport } from './routes/companion.floating'

const TtsRoute = TtsRouteImport.update({
  id: '/tts',
  path: '/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const SoftwareCenterRoute = SoftwareCenterRouteImport.update({
  id: '/software-center',
  path: '/software-center',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupWizardRoute = SetupWizardRouteImport.update({
  id: '/setup-wizard',
  path: '/setup-wizard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RedeemRoute = RedeemRouteImport.update({
  id: '/redeem',
  path: '/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LinkRoute = LinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const KeysRoute = KeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DevConfigRoute = DevConfigRouteImport.update({
  id: '/dev-config',
  path: '/dev-config',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsStarOfficeUiRoute = LabsStarOfficeUiRouteImport.update({
  id: '/star-office-ui',
  path: '/star-office-ui',
  getParentRoute: () => LabsRoute,
} as any)
const LabsOllamaQwen35Route = LabsOllamaQwen35RouteImport.update({
  id: '/ollama-qwen35',
  path: '/ollama-qwen35',
  getParentRoute: () => LabsRoute,
} as any)
const LabsCompanionRoute = LabsCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => LabsRoute,
} as any)
const CompanionFloatingRoute = CompanionFloatingRouteImport.update({
  id: '/companion/floating',
  path: '/companion/floating',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/dev-config': typeof DevConfigRoute
  '/discover': typeof DiscoverRoute
  '/keys': typeof KeysRoute
  '/labs': typeof LabsRouteWithChildren
  '/link': typeof LinkRoute
  '/logs': typeof LogsRoute
  '/redeem': typeof RedeemRoute
  '/settings': typeof SettingsRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/software-center': typeof SoftwareCenterRoute
  '/tts': typeof TtsRoute
  '/companion/floating': typeof CompanionFloatingRoute
  '/labs/companion': typeof LabsCompanionRoute
  '/labs/ollama-qwen35': typeof LabsOllamaQwen35Route
  '/labs/star-office-ui': typeof LabsStarOfficeUiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/dev-config': typeof DevConfigRoute
  '/discover': typeof DiscoverRoute
  '/keys': typeof KeysRoute
  '/labs': typeof LabsRouteWithChildren
  '/link': typeof LinkRoute
  '/logs': typeof LogsRoute
  '/redeem': typeof RedeemRoute
  '/settings': typeof SettingsRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/software-center': typeof SoftwareCenterRoute
  '/tts': typeof TtsRoute
  '/companion/floating': typeof CompanionFloatingRoute
  '/labs/companion': typeof LabsCompanionRoute
  '/labs/ollama-qwen35': typeof LabsOllamaQwen35Route
  '/labs/star-office-ui': typeof LabsStarOfficeUiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/channels': typeof ChannelsRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/dev-config': typeof DevConfigRoute
  '/discover': typeof DiscoverRoute
  '/keys': typeof KeysRoute
  '/labs': typeof LabsRouteWithChildren
  '/link': typeof LinkRoute
  '/logs': typeof LogsRoute
  '/redeem': typeof RedeemRoute
  '/settings': typeof SettingsRoute
  '/setup-wizard': typeof SetupWizardRoute
  '/software-center': typeof SoftwareCenterRoute
  '/tts': typeof TtsRoute
  '/companion/floating': typeof CompanionFloatingRoute
  '/labs/companion': typeof LabsCompanionRoute
  '/labs/ollama-qwen35': typeof LabsOllamaQwen35Route
  '/labs/star-office-ui': typeof LabsStarOfficeUiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/channels'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/dev-config'
    | '/discover'
    | '/keys'
    | '/labs'
    | '/link'
    | '/logs'
    | '/redeem'
    | '/settings'
    | '/setup-wizard'
    | '/software-center'
    | '/tts'
    | '/companion/floating'
    | '/labs/companion'
    | '/labs/ollama-qwen35'
    | '/labs/star-office-ui'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/channels'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/dev-config'
    | '/discover'
    | '/keys'
    | '/labs'
    | '/link'
    | '/logs'
    | '/redeem'
    | '/settings'
    | '/setup-wizard'
    | '/software-center'
    | '/tts'
    | '/companion/floating'
    | '/labs/companion'
    | '/labs/ollama-qwen35'
    | '/labs/star-office-ui'
  id:
    | '__root__'
    | '/'
    | '/channels'
    | '/chat'
    | '/community'
    | '/dashboard'
    | '/dev-config'
    | '/discover'
    | '/keys'
    | '/labs'
    | '/link'
    | '/logs'
    | '/redeem'
    | '/settings'
    | '/setup-wizard'
    | '/software-center'
    | '/tts'
    | '/companion/floating'
    | '/labs/companion'
    | '/labs/ollama-qwen35'
    | '/labs/star-office-ui'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChannelsRoute: typeof ChannelsRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  DevConfigRoute: typeof DevConfigRoute
  DiscoverRoute: typeof DiscoverRoute
  KeysRoute: typeof KeysRoute
  LabsRoute: typeof LabsRouteWithChildren
  LinkRoute: typeof LinkRoute
  LogsRoute: typeof LogsRoute
  RedeemRoute: typeof RedeemRoute
  SettingsRoute: typeof SettingsRoute
  SetupWizardRoute: typeof SetupWizardRoute
  SoftwareCenterRoute: typeof SoftwareCenterRoute
  TtsRoute: typeof TtsRoute
  CompanionFloatingRoute: typeof CompanionFloatingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tts': {
      id: '/tts'
      path: '/tts'
      fullPath: '/tts'
      preLoaderRoute: typeof TtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/software-center': {
      id: '/software-center'
      path: '/software-center'
      fullPath: '/software-center'
      preLoaderRoute: typeof SoftwareCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-wizard': {
      id: '/setup-wizard'
      path: '/setup-wizard'
      fullPath: '/setup-wizard'
      preLoaderRoute: typeof SetupWizardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redeem': {
      id: '/redeem'
      path: '/redeem'
      fullPath: '/redeem'
      preLoaderRoute: typeof RedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/link': {
      id: '/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof LinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-config': {
      id: '/dev-config'
      path: '/dev-config'
      fullPath: '/dev-config'
      preLoaderRoute: typeof DevConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/star-office-ui': {
      id: '/labs/star-office-ui'
      path: '/star-office-ui'
      fullPath: '/labs/star-office-ui'
      preLoaderRoute: typeof LabsStarOfficeUiRouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/ollama-qwen35': {
      id: '/labs/ollama-qwen35'
      path: '/ollama-qwen35'
      fullPath: '/labs/ollama-qwen35'
      preLoaderRoute: typeof LabsOllamaQwen35RouteImport
      parentRoute: typeof LabsRoute
    }
    '/labs/companion': {
      id: '/labs/companion'
      path: '/companion'
      fullPath: '/labs/companion'
      preLoaderRoute: typeof LabsCompanionRouteImport
      parentRoute: typeof LabsRoute
    }
    '/companion/floating': {
      id: '/companion/floating'
      path: '/companion/floating'
      fullPath: '/companion/floating'
      preLoaderRoute: typeof CompanionFloatingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LabsRouteChildren {
  LabsCompanionRoute: typeof LabsCompanionRoute
  LabsOllamaQwen35Route: typeof LabsOllamaQwen35Route
  LabsStarOfficeUiRoute: typeof LabsStarOfficeUiRoute
}

const LabsRouteChildren: LabsRouteChildren = {
  LabsCompanionRoute: LabsCompanionRoute,
  LabsOllamaQwen35Route: LabsOllamaQwen35Route,
  LabsStarOfficeUiRoute: LabsStarOfficeUiRoute,
}

const LabsRouteWithChildren = LabsRoute._addFileChildren(LabsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChannelsRoute: ChannelsRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  DevConfigRoute: DevConfigRoute,
  DiscoverRoute: DiscoverRoute,
  KeysRoute: KeysRoute,
  LabsRoute: LabsRouteWithChildren,
  LinkRoute: LinkRoute,
  LogsRoute: LogsRoute,
  RedeemRoute: RedeemRoute,
  SettingsRoute: SettingsRoute,
  SetupWizardRoute: SetupWizardRoute,
  SoftwareCenterRoute: SoftwareCenterRoute,
  TtsRoute: TtsRoute,
  CompanionFloatingRoute: CompanionFloatingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
