export function bashRuntimeProbePrelude() {
  // Keep in sync with daemon `bash_runtime_probe_prelude()` (Rust).
  return [
    'export PATH="${HOME}/.holycrab/bin:${HOME}/.volta/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${HOME}/.local/bin:${PATH:-}"',
    'export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"',
    'nvm_script=""',
    'for candidate in "$NVM_DIR/nvm.sh" "$HOME/.nvm/nvm.sh" "/opt/homebrew/opt/nvm/nvm.sh" "/usr/local/opt/nvm/nvm.sh"; do',
    '  if [ -s "$candidate" ]; then nvm_script="$candidate"; break; fi',
    'done',
    'if [ -n "$nvm_script" ]; then . "$nvm_script" >/dev/null 2>&1; nvm use --silent default >/dev/null 2>&1 || true; fi',
  ].join('\n')
}

export function bashNodeRuntimeProbeSnippet() {
  return [
    'probe_node_path="$(command -v node 2>/dev/null || true)"',
    'probe_npm_path="$(command -v npm 2>/dev/null || true)"',
    'probe_node_version="$(node -v 2>/dev/null || true)"',
    'probe_npm_version="$(npm -v 2>/dev/null || true)"',
    'probe_manager="unknown"',
    'case "${probe_node_path}" in',
    '  "$HOME"/.nvm/*) probe_manager="nvm" ;;',
    '  "$HOME"/.volta/*) probe_manager="volta" ;;',
    '  /opt/homebrew/*|/usr/local/*) probe_manager="brew/system" ;;',
    '  "") probe_manager="missing" ;;',
    'esac',
    'echo "Node runtime probe: manager=${probe_manager} node=${probe_node_version:-missing} npm=${probe_npm_version:-missing} node_path=${probe_node_path:-missing} npm_path=${probe_npm_path:-missing}"',
  ].join('\n')
}

export function bashEnsureNodeAndNpmSnippet() {
  // User-space install only (no sudo). Works in bash --noprofile --norc.
  // Enforces Node >= 22 and picks an upgrade path that respects existing managers.
  return [
    'export PATH="${HOME}/.holycrab/bin:${HOME}/.volta/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:${HOME}/.local/bin:${PATH:-}"',
    'export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"',
    'min_node_major="22"',
    'mkdir -p "$HOME/.holycrab/bin" >/dev/null 2>&1 || true',
    'mkdir -p "$HOME/.local/bin" >/dev/null 2>&1 || true',
    'echo "$ checking node/npm..."',
    'resolve_nvm_script() {',
    '  for candidate in "${NVM_DIR}/nvm.sh" "$HOME/.nvm/nvm.sh" "/opt/homebrew/opt/nvm/nvm.sh" "/usr/local/opt/nvm/nvm.sh"; do',
    '    if [ -s "$candidate" ]; then',
    '      printf "%s" "$candidate"',
    '      return 0',
    '    fi',
    '  done',
    '  return 1',
    '}',
    'load_nvm_default() {',
    '  nvm_script="$(resolve_nvm_script || true)"',
    '  if [ -n "${nvm_script}" ]; then',
    '    . "${nvm_script}" >/dev/null 2>&1 || true',
    '    nvm use --silent default >/dev/null 2>&1 || true',
    '    return 0',
    '  fi',
    '  return 1',
    '}',
    'node_probe() {',
    '  probe_tag="${1:-probe}"',
    '  probe_node_path="$(command -v node 2>/dev/null || true)"',
    '  probe_npm_path="$(command -v npm 2>/dev/null || true)"',
    '  probe_node_version="$(node -v 2>/dev/null || true)"',
    '  probe_npm_version="$(npm -v 2>/dev/null || true)"',
    '  probe_manager="unknown"',
    '  case "${probe_node_path}" in',
    '    "$HOME"/.nvm/*) probe_manager="nvm" ;;',
    '    "$HOME"/.volta/*) probe_manager="volta" ;;',
    '    /opt/homebrew/*|/usr/local/*) probe_manager="brew/system" ;;',
    '    "") probe_manager="missing" ;;',
    '  esac',
    '  echo "Node runtime ${probe_tag}: manager=${probe_manager} node=${probe_node_version:-missing} npm=${probe_npm_version:-missing} node_path=${probe_node_path:-missing} npm_path=${probe_npm_path:-missing}"',
    '}',
    'detect_node_major() {',
    '  if ! command -v node >/dev/null 2>&1; then',
    '    echo "0"',
    '    return 0',
    '  fi',
    '  v="$(node -v 2>/dev/null || true)"',
    '  v="${v#v}"',
    '  v="${v%%.*}"',
    '  case "$v" in',
    '    ""|*[!0-9]*) echo "0" ;;',
    '    *) echo "$v" ;;',
    '  esac',
    '}',
    'load_nvm_default || true',
    'node_probe "before"',
    'node_path="$(command -v node 2>/dev/null || true)"',
    'node_major="$(detect_node_major)"',
    'using_nvm="0"',
    'using_volta="0"',
    'if [ -n "${node_path}" ] && [ "${node_path#${HOME}/.nvm/}" != "${node_path}" ]; then using_nvm="1"; fi',
    'if [ -n "${node_path}" ] && [ "${node_path#${HOME}/.volta/}" != "${node_path}" ]; then using_volta="1"; fi',
    'if [ -x "$HOME/.volta/bin/volta" ] || command -v volta >/dev/null 2>&1; then using_volta="1"; fi',
    'has_nvm_script="0"',
    'if resolve_nvm_script >/dev/null 2>&1 || [ "$using_nvm" = "1" ]; then has_nvm_script="1"; fi',
    'needs_node_prepare="0"',
    'if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then',
    '  needs_node_prepare="1"',
    '  echo "Node.js/npm not found. Preparing Node.js >= ${min_node_major}..."',
    'elif [ "${node_major:-0}" -lt "${min_node_major}" ] 2>/dev/null; then',
    '  needs_node_prepare="1"',
    '  echo "Node.js $(node -v 2>/dev/null || echo unknown) is below required v${min_node_major}. Upgrading..."',
    'fi',
    'if [ "$needs_node_prepare" = "1" ]; then',
    '  manager="volta"',
    '  if [ "$has_nvm_script" = "1" ]; then',
    '    manager="nvm"',
    '  elif [ "$using_volta" = "1" ]; then',
    '    manager="volta"',
    '  elif [ -n "${node_path}" ] && command -v brew >/dev/null 2>&1; then',
    '    case "${node_path}" in',
    '      /opt/homebrew/*|/usr/local/*) manager="brew" ;;',
    '      *) manager="volta" ;;',
    '    esac',
    '  fi',
    '  if [ "$manager" = "nvm" ]; then',
    '    if ! resolve_nvm_script >/dev/null 2>&1; then',
    '      echo "Installing nvm into $NVM_DIR..."',
    '      mkdir -p "$NVM_DIR" >/dev/null 2>&1 || true',
    '      if command -v git >/dev/null 2>&1; then',
    '        tmpdir="$(mktemp -d 2>/dev/null || mktemp -d -t holycrab)"',
    '        if git clone --depth 1 --branch v0.39.7 https://github.com/nvm-sh/nvm.git "$tmpdir/nvm.git" >/dev/null 2>&1; then',
    '          cp -R "$tmpdir/nvm.git/." "$NVM_DIR/"',
    '        fi',
    '        rm -rf "$tmpdir" >/dev/null 2>&1 || true',
    '      fi',
    '      if ! resolve_nvm_script >/dev/null 2>&1 && command -v curl >/dev/null 2>&1; then',
    '        tmpdir="$(mktemp -d 2>/dev/null || mktemp -d -t holycrab)"',
    '        echo "Downloading nvm tarball..."',
    '        curl -fsSL https://github.com/nvm-sh/nvm/archive/refs/tags/v0.39.7.tar.gz -o "$tmpdir/nvm.tgz"',
    '        tar -xzf "$tmpdir/nvm.tgz" -C "$tmpdir"',
    '        cp -R "$tmpdir/nvm-0.39.7/." "$NVM_DIR/"',
    '        rm -rf "$tmpdir" >/dev/null 2>&1 || true',
    '      fi',
    '    fi',
    '    load_nvm_default || true',
    '    if command -v nvm >/dev/null 2>&1; then',
    '      echo "$ nvm install 22 --latest-npm"',
    '      nvm install 22 --latest-npm',
    '      echo "$ nvm alias default 22"',
    '      nvm alias default 22 >/dev/null 2>&1 || true',
    '      nvm use --silent 22 >/dev/null 2>&1 || nvm use --silent default >/dev/null 2>&1 || true',
    '      hash -r || true',
    '    else',
    '      echo "nvm could not be loaded after installation attempt."',
    '    fi',
    '  elif [ "$manager" = "brew" ]; then',
    '    echo "Upgrading Node.js via Homebrew..."',
    '    echo "$ brew upgrade node || brew install node"',
    '    brew upgrade node >/dev/null 2>&1 || brew install node',
    '    hash -r || true',
    '  else',
    '    export PATH="$HOME/.volta/bin:${PATH:-}"',
    '    if ! command -v volta >/dev/null 2>&1; then',
    '      if command -v curl >/dev/null 2>&1; then',
    '        echo "$ curl -fsSL https://get.volta.sh | bash"',
    '        curl -fsSL https://get.volta.sh | bash',
    '        export PATH="$HOME/.volta/bin:${PATH:-}"',
    '      fi',
    '    fi',
    '    if command -v volta >/dev/null 2>&1; then',
    '      echo "$ volta install node@22"',
    '      volta install node@22',
    '      hash -r || true',
    '    fi',
    '  fi',
    'fi',
    'load_nvm_default || true',
    'node_path="$(command -v node 2>/dev/null || true)"',
    'if [ -n "${node_path}" ] && [ "${node_path#${HOME}/.nvm/}" != "${node_path}" ]; then',
    '  using_nvm="1"',
    'else',
    '  using_nvm="0"',
    'fi',
    // Only set npm prefix when NOT using nvm. nvm exits if `prefix` is set.
    'if [ "${using_nvm}" = "0" ]; then',
    '  export npm_config_prefix="${npm_config_prefix:-$HOME/.local}"',
    '  export PATH="$HOME/.local/bin:${PATH:-}"',
    '  hash -r || true',
    'fi',
    'if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then',
    '  echo "Failed to provision Node.js/npm. Please install Node.js manually and retry."',
    '  exit 1',
    'fi',
    'node_major="$(detect_node_major)"',
    'if [ "${node_major:-0}" -lt "${min_node_major}" ] 2>/dev/null; then',
    '  echo "Node.js is still below v${min_node_major} after preparation (found: $(node -v 2>/dev/null || echo unknown))."',
    '  exit 1',
    'fi',
    'node_probe "after"',
    'echo "Node: $(node -v 2>/dev/null || echo unknown) | npm: $(npm -v 2>/dev/null || echo unknown)"',
  ].join('\n')
}

export function bashNoProfileNoRcArgv(script: string) {
  return ['/bin/bash', '--noprofile', '--norc', '-c', script]
}

export type ShellKind = 'bash' | 'powershell'

export function shellKindForPlatform(platform: string) {
  const normalized = (platform || '').trim().toLowerCase()
  if (normalized === 'windows' || normalized.startsWith('win')) {
    return 'powershell'
  }
  return 'bash'
}

export function shellArgvForScript(script: string, shellKind: ShellKind) {
  if (shellKind === 'powershell') {
    return [
      'powershell.exe',
      '-NoLogo',
      '-NoProfile',
      '-ExecutionPolicy',
      'Bypass',
      '-Command',
      script,
    ]
  }
  return bashNoProfileNoRcArgv(script)
}
