import { bashRuntimeProbePrelude } from '@/lib/bash'

export interface OllamaLabModelOption {
  id: string
  label: string
}

export const OLLAMA_LAB_QWEN35_MODEL_OPTIONS: OllamaLabModelOption[] = [
  { id: 'qwen3.5:0.8b', label: 'Qwen3.5 0.8B' },
  { id: 'qwen3.5:2b', label: 'Qwen3.5 2B' },
  { id: 'qwen3.5:4b', label: 'Qwen3.5 4B' },
  { id: 'qwen3.5:9b', label: 'Qwen3.5 9B' },
]

export interface BuildOllamaLabScriptOptions {
  modelIds?: string[]
}

function normalizeModelIds(modelIds?: string[]) {
  const fallback = OLLAMA_LAB_QWEN35_MODEL_OPTIONS.map((item) => item.id)
  const source = Array.isArray(modelIds) && modelIds.length > 0 ? modelIds : fallback
  const deduped = new Set<string>()

  for (const item of source) {
    const normalized = String(item || '').trim()
    if (normalized) {
      deduped.add(normalized)
    }
  }

  return Array.from(deduped)
}

function quoteBashSingle(value: string) {
  return `'${value.replace(/'/g, `'"'"'`)}'`
}

function quotePowerShellSingle(value: string) {
  return `'${value.replace(/'/g, "''")}'`
}

export function buildOllamaLabScriptUnix(options: BuildOllamaLabScriptOptions = {}) {
  const prelude = bashRuntimeProbePrelude()
  const modelIds = normalizeModelIds(options.modelIds)
  const modelArray = modelIds.map(quoteBashSingle).join(' ')

  return [
    'set -euo pipefail',
    'log() { echo "[ollama-lab] $*"; }',
    'fail() { echo "[ollama-lab] ERROR: $*" >&2; exit 1; }',
    'upgrade_performed="0"',
    'current_ollama_version=""',
    'latest_ollama_version=""',
    'extract_ollama_version() {',
    '  local raw="$1"',
    "  echo \"$raw\" | sed -n 's/.*version is \\{0,1\\}\\([0-9][0-9.]*\\).*/\\1/p' | head -n 1",
    '}',
    'install_ollama_official() {',
    '  local output status',
    '  set +e',
    '  output="$(curl -fsSL https://ollama.com/install.sh 2>&1 | sh 2>&1)"',
    '  status=$?',
    '  set -e',
    '  if [ "$status" -eq 0 ]; then',
    '    upgrade_performed="1"',
    '    return 0',
    '  fi',
    '  return 1',
    '}',
    'install_or_upgrade_ollama() {',
    '  local reason="${1:-upgrade}"',
    '  if install_ollama_official; then',
    '    return 0',
    '  fi',
    '  if [ "$(uname -s 2>/dev/null || echo unknown)" = "Darwin" ] && command -v brew >/dev/null 2>&1; then',
    '    log "Official channel unavailable, trying Homebrew for ${reason}..."',
    '    set +e',
    '    HOMEBREW_NO_AUTO_UPDATE=1 brew upgrade ollama >/dev/null 2>&1',
    '    local brew_status=$?',
    '    if [ "$brew_status" -ne 0 ]; then',
    '      HOMEBREW_NO_AUTO_UPDATE=1 brew install ollama >/dev/null 2>&1',
    '      brew_status=$?',
    '    fi',
    '    set -e',
    '    if [ "$brew_status" -eq 0 ]; then',
    '      upgrade_performed="1"',
      '      return 0',
    '    fi',
    '  fi',
    '  fail "Unable to ${reason} Ollama automatically. Please upgrade Ollama manually from https://ollama.com/download and rerun."',
    '}',
    'refresh_ollama_versions() {',
    '  local current_raw',
    '  current_raw="$(ollama --version 2>/dev/null || true)"',
    '  current_ollama_version="$(extract_ollama_version "$current_raw")"',
    '  latest_ollama_version="$(curl -fsSL https://api.github.com/repos/ollama/ollama/releases/latest 2>/dev/null | sed -n \'s/.*"tag_name"[[:space:]]*:[[:space:]]*"v\\([0-9][^"]*\\)".*/\\1/p\' | head -n 1)"',
    '}',
    'start_ollama_service() {',
    '  log "Starting Ollama service in background..."',
    '  mkdir -p "$HOME/.ollama/logs" >/dev/null 2>&1 || true',
    '  nohup ollama serve >>"$HOME/.ollama/logs/ollama-serve.log" 2>&1 &',
    '}',
    'wait_ollama_ready() {',
    '  local ready="0" attempt="0"',
    '  log "Waiting for Ollama API (http://127.0.0.1:11434/api/tags)..."',
    '  while [ "$attempt" -lt 30 ]; do',
    '    if curl -fsS http://127.0.0.1:11434/api/tags >/dev/null 2>&1; then',
    '      ready="1"',
    '      break',
    '    fi',
    '    attempt=$((attempt + 1))',
    '    sleep 1',
    '  done',
    '  if [ "$ready" != "1" ]; then',
    '    fail "Ollama service did not become ready within 30s."',
    '  fi',
    '}',
    'restart_ollama_service_if_needed() {',
    '  if pgrep -x ollama >/dev/null 2>&1 && [ "${upgrade_performed}" = "1" ]; then',
    '    log "Restarting Ollama service after upgrade..."',
    '    pkill -x ollama >/dev/null 2>&1 || true',
    '    sleep 1',
    '  fi',
    '  if ! pgrep -x ollama >/dev/null 2>&1; then',
    '    start_ollama_service',
    '  fi',
    '}',
    'force_upgrade_ollama() {',
    '  refresh_ollama_versions',
    '  if [ "${OLLAMA_LAB_FORCE_UPGRADE:-0}" = "1" ]; then',
    '    log "Force upgrade enabled; upgrading Ollama..."',
    '    install_or_upgrade_ollama "upgrade"',
    '    refresh_ollama_versions',
    '    return 0',
    '  fi',
    '  if [ -n "$current_ollama_version" ] && [ -n "$latest_ollama_version" ] && [ "$current_ollama_version" = "$latest_ollama_version" ]; then',
    '    log "Ollama already up to date (${current_ollama_version})."',
    '    return 0',
    '  fi',
    '  if [ -n "$current_ollama_version" ] && [ -n "$latest_ollama_version" ]; then',
    '    log "Upgrading Ollama (current=${current_ollama_version}, latest=${latest_ollama_version})..."',
    '    install_or_upgrade_ollama "upgrade"',
    '    refresh_ollama_versions',
    '    return 0',
    '  fi',
    '  log "Skipping proactive upgrade (version metadata unavailable)."',
    '}',
    'pull_model_with_auto_update() {',
    '  local model="$1"',
    '  local output status',
    '  set +e',
    '  output="$(ollama pull "$model" 2>&1)"',
    '  status=$?',
    '  set -e',
    '  [ -n "$output" ] && echo "$output"',
    '  if [ "$status" -ne 0 ] && echo "$output" | grep -qi "requires a newer version of Ollama"; then',
    '    refresh_ollama_versions',
    '    if [ -n "$current_ollama_version" ] && [ -n "$latest_ollama_version" ] && [ "$current_ollama_version" = "$latest_ollama_version" ]; then',
    '      fail "Model ${model} requires a newer Ollama than current stable (${current_ollama_version}). Please switch model or wait for next Ollama release."',
    '    fi',
    '    log "Detected outdated Ollama while pulling ${model}; upgrading and retrying..."',
    '    install_or_upgrade_ollama "upgrade"',
    '    upgrade_performed="1"',
    '    refresh_ollama_versions',
    '    restart_ollama_service_if_needed',
    '    wait_ollama_ready',
    '    set +e',
    '    output="$(ollama pull "$model" 2>&1)"',
    '    status=$?',
    '    set -e',
    '    [ -n "$output" ] && echo "$output"',
    '  fi',
    '  if [ "$status" -ne 0 ]; then',
    '    local last_line',
    '    last_line="$(echo "$output" | tail -n 1 | tr -d "\\r")"',
    '    if [ -n "$last_line" ]; then',
    '      fail "Failed to pull model ${model}: ${last_line}"',
    '    fi',
    '    fail "Failed to pull model ${model}. Please check network/model id and try again."',
    '  fi',
    '}',
    '',
    'log "Preparing environment..."',
    prelude,
    '',
    'if ! command -v curl >/dev/null 2>&1; then',
    '  fail "curl is required but was not found."',
    'fi',
    '',
    'if ! command -v ollama >/dev/null 2>&1; then',
    '  os_name="$(uname -s 2>/dev/null || echo unknown)"',
    '  case "${os_name}" in',
    '    Darwin|Linux)',
    '      log "Ollama not found. Installing..."',
    '      install_or_upgrade_ollama "install"',
    '      ;;',
    '    *)',
    '      fail "Unsupported OS for auto-install: ${os_name}. Please install Ollama manually."',
    '      ;;',
    '  esac',
    'fi',
    '',
    'if ! command -v ollama >/dev/null 2>&1; then',
    '  fail "Ollama command still not found after installation."',
    'fi',
    '',
    'force_upgrade_ollama',
    '',
    'restart_ollama_service_if_needed',
    'wait_ollama_ready',
    '',
    `models=(${modelArray})`,
    'for model in "${models[@]}"; do',
    '  log "Pulling model: ${model}"',
    '  pull_model_with_auto_update "${model}"',
    'done',
    '',
    'log "Final status:"',
    'echo "$ ollama --version"',
    'ollama --version',
    'echo "$ ollama list"',
    'ollama list',
    'log "Completed."',
  ].join('\n')
}

export function buildOllamaLabScriptWindows(options: BuildOllamaLabScriptOptions = {}) {
  const modelIds = normalizeModelIds(options.modelIds)
  const modelArray = modelIds.map(quotePowerShellSingle).join(', ')

  return [
    '$ErrorActionPreference = "Stop"',
    'Set-StrictMode -Version Latest',
    '',
    'function Write-Step([string]$Message) {',
    '  Write-Host ("[ollama-lab] " + $Message)',
    '}',
    '',
    'function Fail-Step([string]$Message) {',
    '  throw ("[ollama-lab] " + $Message)',
    '}',
    '',
    'function Get-OllamaCommand {',
    '  return Get-Command ollama -ErrorAction SilentlyContinue',
    '}',
    '',
    'function Force-UpgradeOllama {',
    '  if ($env:OLLAMA_LAB_SKIP_FORCE_UPGRADE -eq "1") {',
    '    return',
    '  }',
    '  $winget = Get-Command winget -ErrorAction SilentlyContinue',
    '  if (-not $winget) {',
    '    Write-Step "winget not found, skipping forced upgrade on Windows."',
    '    return',
    '  }',
    '  Write-Step "Upgrading Ollama to latest..."',
    '  try {',
    '    & $winget.Source upgrade --id Ollama.Ollama -e --accept-package-agreements --accept-source-agreements *> $null',
    '  } catch {',
    '    # if upgrade command fails, fallback to install command',
    '    try {',
    '      & $winget.Source install --id Ollama.Ollama -e --accept-package-agreements --accept-source-agreements *> $null',
    '    } catch {',
    '      # ignore upgrade errors and continue',
    '    }',
    '  }',
    '}',
    '',
    'Write-Step "Preparing environment..."',
    '$ollama = Get-OllamaCommand',
    'if (-not $ollama) {',
    '  Write-Step "Ollama not found. Installing..."',
    '  $winget = Get-Command winget -ErrorAction SilentlyContinue',
    '  if ($winget) {',
    '    Write-Host "$ winget install --id Ollama.Ollama -e --accept-package-agreements --accept-source-agreements"',
    '    & $winget.Source install --id Ollama.Ollama -e --accept-package-agreements --accept-source-agreements',
    '  } else {',
    '    $installerUrl = "https://ollama.com/download/OllamaSetup.exe"',
    '    $installerPath = Join-Path $env:TEMP "OllamaSetup.exe"',
    '    Write-Host ("$ curl.exe -L " + $installerUrl + " -o " + $installerPath)',
    '    curl.exe -L $installerUrl -o $installerPath',
    `    Write-Host ("$ Start-Process -FilePath " + $installerPath + " -ArgumentList '/S' -Wait")`,
    '    Start-Process -FilePath $installerPath -ArgumentList "/S" -Wait',
    '  }',
    '  $ollama = Get-OllamaCommand',
    '}',
    '',
    'if (-not $ollama) {',
    '  Fail-Step "Ollama command still not found after installation."',
    '}',
    '',
    'Force-UpgradeOllama',
    '$ollama = Get-OllamaCommand',
    'if (-not $ollama) {',
    '  Fail-Step "Ollama command not found after update check."',
    '}',
    '',
    '$ollamaExe = $ollama.Source',
    '$process = Get-Process -Name ollama -ErrorAction SilentlyContinue | Select-Object -First 1',
    'if (-not $process) {',
    '  Write-Step "Starting Ollama service in background..."',
    '  Start-Process -FilePath $ollamaExe -ArgumentList "serve" -WindowStyle Hidden',
    '}',
    '',
    'Write-Step "Waiting for Ollama API (http://127.0.0.1:11434/api/tags)..."',
    '$ready = $false',
    'for ($i = 0; $i -lt 30; $i++) {',
    '  try {',
    '    Invoke-WebRequest -Uri "http://127.0.0.1:11434/api/tags" -UseBasicParsing -TimeoutSec 2 *> $null',
    '    $ready = $true',
    '    break',
    '  } catch {',
    '    Start-Sleep -Seconds 1',
    '  }',
    '}',
    '',
    'if (-not $ready) {',
    '  Fail-Step "Ollama service did not become ready within 30s."',
    '}',
    '',
    `$modelIds = @(${modelArray})`,
    'foreach ($model in $modelIds) {',
    '  Write-Step ("Pulling model: " + $model)',
    '  $pullOutput = & $ollamaExe pull $model 2>&1 | Out-String',
    '  if (-not [string]::IsNullOrWhiteSpace($pullOutput)) {',
    '    Write-Host $pullOutput',
    '  }',
    '  $pullExitCode = $LASTEXITCODE',
    '  if ($pullExitCode -ne 0 -and $pullOutput -match "requires a newer version of Ollama") {',
    '    Write-Step ("Detected outdated Ollama while pulling " + $model + "; upgrading and retrying...")',
    '    Force-UpgradeOllama',
    '    $ollama = Get-OllamaCommand',
    '    if (-not $ollama) {',
    '      Fail-Step "Ollama command not found after retry update."',
    '    }',
    '    $ollamaExe = $ollama.Source',
    '    $pullOutput = & $ollamaExe pull $model 2>&1 | Out-String',
    '    if (-not [string]::IsNullOrWhiteSpace($pullOutput)) {',
    '      Write-Host $pullOutput',
    '    }',
    '    $pullExitCode = $LASTEXITCODE',
    '  }',
    '  if ($pullExitCode -ne 0) {',
    '    $lastLine = ($pullOutput -split "`r?`n" | Where-Object { $_.Trim().Length -gt 0 } | Select-Object -Last 1)',
    '    if ($lastLine) {',
    '      Fail-Step ("Failed to pull model " + $model + ": " + $lastLine)',
    '    }',
    '    Fail-Step ("Failed to pull model " + $model + ". Please check network/model id and try again.")',
    '  }',
    '}',
    '',
    'Write-Step "Final status:"',
    'Write-Host ("$ " + $ollamaExe + " --version")',
    '& $ollamaExe --version',
    'Write-Host ("$ " + $ollamaExe + " list")',
    '& $ollamaExe list',
    'Write-Step "Completed."',
  ].join('\n')
}
