import { bashRuntimeProbePrelude } from '@/lib/bash'

type OpenClawInstallerScriptOptions = {
  notOnPathMessage?: string
  tipRunMessage?: string
}

const OFFICIAL_INSTALL_SCRIPT_UNIX = 'https://openclaw.ai/install.sh'
const OFFICIAL_INSTALL_SCRIPT_WINDOWS = 'https://openclaw.ai/install.ps1'
const OFFICIAL_GITHUB_RELEASES = 'https://github.com/openclaw/openclaw/releases'
const OFFICIAL_NPM_REGISTRY = 'https://registry.npmjs.org/openclaw/latest'

const FALLBACK_PUBLIC_BASE = 'https://d3aus51320hy9f.cloudfront.net/openclaw-installer'
const FALLBACK_INSTALL_SCRIPT_UNIX = `${FALLBACK_PUBLIC_BASE}/install-hc.sh`
const FALLBACK_INSTALL_SCRIPT_WINDOWS = `${FALLBACK_PUBLIC_BASE}/install-hc.ps1`
const FALLBACK_OPENCLAW_PACKAGE = `${FALLBACK_PUBLIC_BASE}/openclaw-latest.tgz`
const FALLBACK_MANIFEST_URL = `${FALLBACK_PUBLIC_BASE}/manifest.json`
const FALLBACK_NPM_REGISTRY = 'https://registry.npmmirror.com'
const FALLBACK_NODE_VERSION_DEFAULT = 'v22.22.0'
const FALLBACK_NODE_BASE = `${FALLBACK_PUBLIC_BASE}/node`

function buildGatewayPostInstallUnix({
  notOnPathMessage,
  tipRunMessage,
}: OpenClawInstallerScriptOptions = {}) {
  const messageNotOnPath = (notOnPathMessage || 'OpenClaw installed, but openclaw is not available in this shell PATH.').replace(/"/g, '\\"')
  const messageTip = (tipRunMessage || 'Tip: open a Terminal and run: openclaw gateway install').replace(/"/g, '\\"')

  return [
    'export PATH="$HOME/.holycrab/bin:$HOME/.local/bin:$PATH"',
    'persist_runtime_path() {',
    '  mkdir -p "$HOME/.holycrab/bin" "$HOME/.local/bin"',
    '  local line=\'export PATH="$HOME/.holycrab/bin:$HOME/.local/bin:$PATH"\'',
    '  for rc in "$HOME/.zprofile" "$HOME/.zshrc" "$HOME/.bash_profile" "$HOME/.bashrc" "$HOME/.profile"; do',
    '    [ -e "$rc" ] || : > "$rc"',
    '    grep -Fqx "$line" "$rc" 2>/dev/null || printf \'\\n%s\\n\' "$line" >> "$rc"',
    '  done',
    '}',
    'resolve_openclaw_bin() {',
    '  local candidate=""',
    '  candidate="$(type -P openclaw || true)"',
    '  if [ -n "$candidate" ] && [ -x "$candidate" ]; then',
    '    printf "%s" "$candidate"',
    '    return 0',
    '  fi',
    '  if [ -n "${npm_config_prefix:-}" ] && [ -x "${npm_config_prefix}/bin/openclaw" ]; then',
    '    printf "%s" "${npm_config_prefix}/bin/openclaw"',
    '    return 0',
    '  fi',
    '  if command -v npm >/dev/null 2>&1; then',
    '    local npm_prefix=""',
    '    npm_prefix="$(npm prefix -g 2>/dev/null || true)"',
    '    if [ -n "$npm_prefix" ] && [ -x "$npm_prefix/bin/openclaw" ]; then',
    '      printf "%s" "$npm_prefix/bin/openclaw"',
    '      return 0',
    '    fi',
    '  fi',
    '  for candidate in "$HOME/.holycrab/bin/openclaw" "$HOME/.local/bin/openclaw"; do',
    '    if [ -x "$candidate" ]; then',
    '      printf "%s" "$candidate"',
    '      return 0',
    '    fi',
    '  done',
    '  return 1',
    '}',
    'ensure_openclaw_shims() {',
    '  local real_bin=""',
    '  real_bin="$(resolve_openclaw_bin || true)"',
    '  if [ -z "$real_bin" ]; then',
    '    return 1',
    '  fi',
    '  case "$real_bin" in',
    '    "$HOME/.holycrab/bin/openclaw")',
    '      ln -sfn "$HOME/.holycrab/bin/openclaw" "$HOME/.local/bin/openclaw"',
    '      return 0',
    '      ;;',
    '    "$HOME/.local/bin/openclaw")',
    '      return 0',
    '      ;;',
    '  esac',
    '  printf \'%s\\n\' \'#!/usr/bin/env bash\' \'set -euo pipefail\' "target=\\"${real_bin}\\"" \'export PATH="$(dirname "$target"):${PATH:-}"\' \'exec "$target" "$@"\' > "$HOME/.holycrab/bin/openclaw"',
    '  chmod +x "$HOME/.holycrab/bin/openclaw"',
    '  ln -sfn "$HOME/.holycrab/bin/openclaw" "$HOME/.local/bin/openclaw"',
    '  hash -r || true',
    '}',
    'persist_runtime_path',
    'ensure_openclaw_shims || true',
    'hash -r || true',
    'hash -r || true',
    'openclaw_bin="$(resolve_openclaw_bin || true)"',
    'if [ -n "${openclaw_bin}" ]; then',
    '  echo "$ ${openclaw_bin} gateway install"',
    '  "${openclaw_bin}" gateway install >/dev/null 2>&1 || true',
    '  echo "$ ${openclaw_bin} gateway restart"',
    '  "${openclaw_bin}" gateway restart >/dev/null 2>&1 || true',
    '  if pgrep -x openclaw-gateway >/dev/null 2>&1; then',
    '    echo "Gateway running."',
    '  else',
    '    echo "$ ${openclaw_bin} gateway run --bind loopback --force (background)"',
    '    mkdir -p /tmp/openclaw',
    '    nohup "${openclaw_bin}" gateway run --bind loopback --force >>/tmp/openclaw/holycrab-openclaw-gateway.log 2>&1 &',
    '  fi',
    'else',
    `  echo "${messageNotOnPath}"`,
    `  echo "${messageTip}"`,
    '  exit 1',
    'fi',
  ].join('\n')
}

export function buildOpenClawInstallScriptUnix(options: OpenClawInstallerScriptOptions = {}) {
  const prelude = bashRuntimeProbePrelude()
  const postInstallGateway = buildGatewayPostInstallUnix(options)

  return [
    'set -euo pipefail',
    'echo "[holycrab] preparing environment..."',
    prelude,
    'openclaw gateway stop >/dev/null 2>&1 || true',
    'pkill -x openclaw-gateway >/dev/null 2>&1 || true',
    'pkill -x openclaw >/dev/null 2>&1 || true',
    '',
    'network_probe() {',
    '  local url="$1"',
    '  curl -fsSIL --connect-timeout 4 --max-time 10 "$url" >/dev/null 2>&1',
    '}',
    '',
    `official_install_url="${OFFICIAL_INSTALL_SCRIPT_UNIX}"`,
    `official_github_url="${OFFICIAL_GITHUB_RELEASES}"`,
    `official_registry_url="${OFFICIAL_NPM_REGISTRY}"`,
    '',
    `fallback_install_url="${FALLBACK_INSTALL_SCRIPT_UNIX}"`,
    `fallback_package_url="${FALLBACK_OPENCLAW_PACKAGE}"`,
    `fallback_npm_registry="${FALLBACK_NPM_REGISTRY}"`,
    `fallback_manifest_url="${FALLBACK_MANIFEST_URL}"`,
    `fallback_node_version_default="${FALLBACK_NODE_VERSION_DEFAULT}"`,
    'fallback_node_version="${fallback_node_version_default}"',
    `fallback_node_base="${FALLBACK_NODE_BASE}"`,
    '',
    'official_ready="1"',
    'for probe_url in "$official_install_url" "$official_github_url" "$official_registry_url"; do',
    '  if ! network_probe "$probe_url"; then',
    '    official_ready="0"',
    '    echo "[holycrab] official precheck failed: $probe_url"',
    '  fi',
    'done',
    '',
    'install_succeeded="0"',
    'if [ "$official_ready" = "1" ]; then',
    '  official_cmd="curl -fsSL ${official_install_url} | bash -s -- --no-prompt --no-onboard"',
    '  echo "$ ${official_cmd}"',
    '  if bash -lc "${official_cmd}"; then',
    '    install_succeeded="1"',
    '    echo "[holycrab] official install succeeded."',
    '  else',
    '    echo "[holycrab] official install failed, switching to fallback path..."',
    '  fi',
    'else',
    '  echo "[holycrab] official install path unavailable, switching to fallback path..."',
    'fi',
    '',
    'if [ "$install_succeeded" != "1" ] && network_probe "$fallback_install_url"; then',
    '  fallback_cmd="curl -fsSL ${fallback_install_url} | bash -s -- --no-prompt --no-onboard"',
    '  echo "$ ${fallback_cmd}"',
    '  if bash -lc "${fallback_cmd}"; then',
    '    install_succeeded="1"',
    '    echo "[holycrab] fallback install.sh succeeded."',
    '  else',
    '    echo "[holycrab] fallback install.sh failed, switching to npm fallback..."',
    '  fi',
    'fi',
    '',
    'resolve_fallback_node_version_from_manifest() {',
    '  if ! network_probe "$fallback_manifest_url"; then',
    '    return 0',
    '  fi',
    '  local detected',
    '  detected="$(curl -fsSL --connect-timeout 6 --max-time 15 "$fallback_manifest_url" | tr -d "\\n\\r" | sed -n \'s/.*"nodeVersion"[[:space:]]*:[[:space:]]*"\\([^\\"[:space:]]*\\)".*/\\1/p\' | head -n 1)"',
    '  if [[ "${detected}" =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$ ]]; then',
    '    fallback_node_version="${detected}"',
    '    echo "[holycrab] fallback node version from manifest: ${fallback_node_version}"',
    '  fi',
    '}',
    '',
    'install_node_from_cloudfront() {',
    '  local os_name arch_name node_file extract_flag',
    '  os_name="$(uname -s | tr "[:upper:]" "[:lower:]")"',
    '  arch_name="$(uname -m)"',
    '  case "${os_name}:${arch_name}" in',
    '    darwin:arm64|darwin:aarch64) node_file="node-${fallback_node_version}-darwin-arm64.tar.gz"; extract_flag="z" ;;',
    '    darwin:x86_64|darwin:amd64) node_file="node-${fallback_node_version}-darwin-x64.tar.gz"; extract_flag="z" ;;',
    '    linux:x86_64|linux:amd64) node_file="node-${fallback_node_version}-linux-x64.tar.xz"; extract_flag="J" ;;',
    '    *) return 1 ;;',
    '  esac',
    '  local dest_dir="$HOME/.holycrab/node/${fallback_node_version}/${os_name}-${arch_name}"',
    '  local bin_dir="$dest_dir/bin"',
    '  if [ -x "$bin_dir/node" ] && [ -x "$bin_dir/npm" ]; then',
    '    export PATH="$bin_dir:$PATH"',
    '    return 0',
    '  fi',
    '  mkdir -p "$dest_dir"',
    '  local tmpdir="$(mktemp -d 2>/dev/null || mktemp -d -t holycrab)"',
    '  local archive="$tmpdir/$node_file"',
    '  local download_url="${fallback_node_base}/${fallback_node_version}/${node_file}"',
    '  echo "$ curl -fsSL ${download_url} -o ${archive}"',
    '  curl -fsSL --connect-timeout 6 --max-time 300 "$download_url" -o "$archive"',
    '  if [ "$extract_flag" = "z" ]; then',
    '    tar -xzf "$archive" --strip-components=1 -C "$dest_dir"',
    '  else',
    '    tar -xJf "$archive" --strip-components=1 -C "$dest_dir"',
    '  fi',
    '  rm -rf "$tmpdir" >/dev/null 2>&1 || true',
    '  export PATH="$bin_dir:$PATH"',
    '  hash -r || true',
    '}',
    '',
    'resolve_fallback_node_version_from_manifest',
    '',
    'ensure_node_runtime_nonfatal() {',
    '  local min_major="${1:-22}"',
    '  local major="0"',
    '  if command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1; then',
    '    major="$(node -v 2>/dev/null | sed "s/^v//" | cut -d. -f1 || echo 0)"',
    '    if [ "${major:-0}" -ge "$min_major" ] 2>/dev/null; then',
    '      return 0',
    '    fi',
    '  fi',
    '  if [ -s "${NVM_DIR:-$HOME/.nvm}/nvm.sh" ]; then',
    '    . "${NVM_DIR:-$HOME/.nvm}/nvm.sh" >/dev/null 2>&1 || true',
    '    if command -v nvm >/dev/null 2>&1; then',
    '      nvm install 22 --latest-npm >/dev/null 2>&1 || true',
    '      nvm use --silent 22 >/dev/null 2>&1 || nvm use --silent default >/dev/null 2>&1 || true',
    '      hash -r || true',
    '    fi',
    '  elif [ -x "$HOME/.volta/bin/volta" ] || command -v volta >/dev/null 2>&1; then',
    '    export PATH="$HOME/.volta/bin:$PATH"',
    '    volta install node@22 >/dev/null 2>&1 || true',
    '    hash -r || true',
    '  elif command -v brew >/dev/null 2>&1; then',
    '    brew upgrade node >/dev/null 2>&1 || brew install node >/dev/null 2>&1 || true',
    '    hash -r || true',
    '  fi',
    '  if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then',
    '    return 1',
    '  fi',
    '  major="$(node -v 2>/dev/null | sed "s/^v//" | cut -d. -f1 || echo 0)"',
    '  [ "${major:-0}" -ge "$min_major" ] 2>/dev/null',
    '}',
    '',
    'if [ "$install_succeeded" != "1" ]; then',
    '  echo "[holycrab] npm fallback: preparing Node.js runtime..."',
    '  if ! ensure_node_runtime_nonfatal 22; then',
    '    echo "[holycrab] local node manager path unavailable, trying CloudFront Node bundle..."',
    '  fi',
    '  node_major="0"',
    '  if command -v node >/dev/null 2>&1; then',
    '    node_major="$(node -v 2>/dev/null | sed "s/^v//" | cut -d. -f1 || echo 0)"',
    '  fi',
    '  if [ "${node_major:-0}" -lt 22 ] 2>/dev/null; then',
    '    echo "[holycrab] local Node runtime still below v22, trying CloudFront Node bundle..."',
    '    install_node_from_cloudfront || true',
    '  fi',
    '  if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then',
    '    echo "[holycrab] Node/npm unavailable after fallback attempts."',
    '    exit 1',
    '  fi',
    '  export npm_config_cache="${npm_config_cache:-$HOME/.holycrab/npm-cache}"',
    '  export npm_config_prefix="${npm_config_prefix:-$HOME/.local}"',
    '  export npm_config_overrides=\'{"@whiskeysockets/baileys":{"libsignal":"npm:libsignal@2.0.1"}}\'',
    '  mkdir -p "$npm_config_cache" "$npm_config_prefix/bin"',
    '  export PATH="$HOME/.local/bin:$PATH"',
    '  hash -r || true',
    '  echo "$ npm install -g openclaw@latest --registry ${fallback_npm_registry}"',
    '  if npm install -g openclaw@latest --registry "${fallback_npm_registry}"; then',
    '    install_succeeded="1"',
    '  else',
    '    if network_probe "$fallback_package_url"; then',
    '      tmpdir="$(mktemp -d 2>/dev/null || mktemp -d -t holycrab)"',
    '      pkg="$tmpdir/openclaw-latest.tgz"',
    '      echo "$ curl -fsSL ${fallback_package_url} -o ${pkg}"',
    '      curl -fsSL --connect-timeout 6 --max-time 180 "$fallback_package_url" -o "$pkg"',
    '      echo "$ npm install -g ${pkg}"',
    '      npm install -g "$pkg"',
    '      rm -rf "$tmpdir" >/dev/null 2>&1 || true',
    '      install_succeeded="1"',
    '    fi',
    '  fi',
    'fi',
    '',
    'if [ "$install_succeeded" != "1" ]; then',
    '  echo "[holycrab] OpenClaw installation failed across all paths."',
    '  exit 1',
    'fi',
    '',
    postInstallGateway,
  ]
    .filter(Boolean)
    .join('\n')
}

export function buildOpenClawInstallScriptWindows(options: OpenClawInstallerScriptOptions = {}) {
  const messageNotOnPath = (options.notOnPathMessage || 'OpenClaw installed, but openclaw is not available in this shell PATH.').replace(/"/g, '`"')

  return [
    '$ErrorActionPreference = "Stop"',
    'Write-Host "[holycrab] preparing environment..."',
    '$openclaw = Get-Command openclaw -ErrorAction SilentlyContinue',
    'if ($openclaw) {',
    '  & $openclaw.Source gateway stop *> $null',
    '}',
    '',
    'function Test-UrlReachable([string]$Url) {',
    '  try {',
    '    Invoke-WebRequest -Uri $Url -Method Head -TimeoutSec 8 *> $null',
    '    return $true',
    '  } catch {',
    '    Write-Host ("[holycrab] precheck failed: " + $Url)',
    '    return $false',
    '  }',
    '}',
    '',
    `$officialInstallUrl = "${OFFICIAL_INSTALL_SCRIPT_WINDOWS}"`,
    `$officialGithubUrl = "${OFFICIAL_GITHUB_RELEASES}"`,
    `$officialRegistryUrl = "${OFFICIAL_NPM_REGISTRY}"`,
    `$fallbackInstallUrl = "${FALLBACK_INSTALL_SCRIPT_WINDOWS}"`,
    `$fallbackRegistry = "${FALLBACK_NPM_REGISTRY}"`,
    `$fallbackPackageUrl = "${FALLBACK_OPENCLAW_PACKAGE}"`,
    `$fallbackManifestUrl = "${FALLBACK_MANIFEST_URL}"`,
    `$fallbackNodeVersionDefault = "${FALLBACK_NODE_VERSION_DEFAULT}"`,
    '$fallbackNodeVersion = $fallbackNodeVersionDefault',
    `$fallbackNodeBase = "${FALLBACK_NODE_BASE}"`,
    '',
    'function Get-NodeMajor {',
    '  $node = Get-Command node -ErrorAction SilentlyContinue',
    '  if (-not $node) { return 0 }',
    '  try {',
    '    $version = & $node.Source -v',
    '    if (-not $version) { return 0 }',
    '    return [int](($version -replace "^v", "").Split(".")[0])',
    '  } catch {',
    '    return 0',
    '  }',
    '}',
    '',
    'function Ensure-NodeRuntime([int]$MinMajor = 22) {',
    '  $node = Get-Command node -ErrorAction SilentlyContinue',
    '  $npm = Get-Command npm -ErrorAction SilentlyContinue',
    '  if ($node -and $npm -and (Get-NodeMajor) -ge $MinMajor) {',
    '    return $true',
    '  }',
    '  $arch = if ([Environment]::Is64BitOperatingSystem) { "x64" } else { "x86" }',
    '  if ($arch -ne "x64") {',
    '    return $false',
    '  }',
    '  $zipName = "node-$fallbackNodeVersion-win-$arch.zip"',
    '  $downloadUrl = $fallbackNodeBase.TrimEnd("/") + "/" + $fallbackNodeVersion + "/" + $zipName',
    '  $destDir = Join-Path $HOME (".holycrab/node/" + $fallbackNodeVersion + "/win-" + $arch)',
    '  $nodeExe = Join-Path $destDir "node.exe"',
    '  $npmCmd = Join-Path $destDir "npm.cmd"',
    '  if (-not ((Test-Path $nodeExe) -and (Test-Path $npmCmd))) {',
    '    if (-not (Test-UrlReachable $downloadUrl)) {',
    '      return $false',
    '    }',
    '    New-Item -ItemType Directory -Force -Path $destDir *> $null',
    '    $tmpZip = Join-Path $env:TEMP $zipName',
    '    $tmpExtract = Join-Path $env:TEMP ("holycrab-node-" + [guid]::NewGuid().ToString("N"))',
    '    Remove-Item $tmpZip -Force -ErrorAction SilentlyContinue',
    '    Remove-Item $tmpExtract -Recurse -Force -ErrorAction SilentlyContinue',
    '    Write-Host ("$ curl -L " + $downloadUrl + " -o " + $tmpZip)',
    '    curl.exe -L $downloadUrl -o $tmpZip',
    '    Expand-Archive -Path $tmpZip -DestinationPath $tmpExtract -Force',
    '    $expandedRoot = Get-ChildItem -Path $tmpExtract -Directory | Select-Object -First 1',
    '    if (-not $expandedRoot) {',
    '      return $false',
    '    }',
    '    Copy-Item -Path (Join-Path $expandedRoot.FullName "*") -Destination $destDir -Recurse -Force',
    '    Remove-Item $tmpZip -Force -ErrorAction SilentlyContinue',
    '    Remove-Item $tmpExtract -Recurse -Force -ErrorAction SilentlyContinue',
    '  }',
    '  if ((Test-Path $nodeExe) -and (Test-Path $npmCmd)) {',
    '    $env:Path = $destDir + ";" + $env:Path',
    '    return (Get-NodeMajor) -ge $MinMajor',
    '  }',
    '  return $false',
    '}',
    '',
    'function Resolve-FallbackNodeVersion {',
    '  try {',
    '    $resp = Invoke-WebRequest -Uri $fallbackManifestUrl -TimeoutSec 8 -UseBasicParsing',
    '    if ($resp -and $resp.Content) {',
    '      $json = $resp.Content | ConvertFrom-Json',
    '      if ($json -and $json.nodeVersion -and ($json.nodeVersion -match "^v\\d+\\.\\d+\\.\\d+$")) {',
    '        $script:fallbackNodeVersion = [string]$json.nodeVersion',
    '        Write-Host ("[holycrab] fallback node version from manifest: " + $script:fallbackNodeVersion)',
    '      }',
    '    }',
    '  } catch {',
    '    # best-effort only',
    '  }',
    '}',
    '',
    'Resolve-FallbackNodeVersion',
    '',
    '$officialReady = (Test-UrlReachable $officialInstallUrl) -and (Test-UrlReachable $officialGithubUrl) -and (Test-UrlReachable $officialRegistryUrl)',
    '$installSucceeded = $false',
    '',
    'if ($officialReady) {',
    '  try {',
    '    $officialCmd = "irm " + $officialInstallUrl + " | iex"',
    '    Write-Host ("$ " + $officialCmd)',
    '    Invoke-Expression $officialCmd',
    '    $installSucceeded = $true',
    '    Write-Host "[holycrab] official install succeeded."',
    '  } catch {',
    '    Write-Host "[holycrab] official install failed, switching to fallback path..."',
    '  }',
    '}',
    '',
    'if (-not $installSucceeded -and (Test-UrlReachable $fallbackInstallUrl)) {',
    '  try {',
    '    $fallbackCmd = "irm " + $fallbackInstallUrl + " | iex"',
    '    Write-Host ("$ " + $fallbackCmd)',
    '    Invoke-Expression $fallbackCmd',
    '    $installSucceeded = $true',
    '    Write-Host "[holycrab] fallback install.ps1 succeeded."',
    '  } catch {',
    '    Write-Host "[holycrab] fallback install.ps1 failed, switching to npm fallback..."',
    '  }',
    '}',
    '',
    'if (-not $installSucceeded) {',
    '  if (-not (Ensure-NodeRuntime 22)) {',
    '    throw "Node.js/npm not found. Install Node.js 22+ first, then retry."',
    '  }',
    '  $node = Get-Command node -ErrorAction SilentlyContinue',
    '  $npm = Get-Command npm -ErrorAction SilentlyContinue',
    '  if (-not $node -or -not $npm) {',
    '    throw "Node.js/npm not found. Install Node.js 22+ first, then retry."',
    '  }',
    '  $env:npm_config_cache = Join-Path $HOME ".holycrab/npm-cache"',
    '  New-Item -ItemType Directory -Force -Path $env:npm_config_cache *> $null',
    '  $env:npm_config_overrides = \'{"@whiskeysockets/baileys":{"libsignal":"npm:libsignal@2.0.1"}}\'',
    '  try {',
    '    Write-Host ("$ npm install -g openclaw@latest --registry " + $fallbackRegistry)',
    '    & $npm.Source install -g openclaw@latest --registry $fallbackRegistry',
    '    $installSucceeded = $true',
    '  } catch {',
    '    if (Test-UrlReachable $fallbackPackageUrl) {',
    '      $tmp = Join-Path $env:TEMP "holycrab-openclaw-latest.tgz"',
    '      Write-Host ("$ curl -L " + $fallbackPackageUrl + " -o " + $tmp)',
    '      curl.exe -L $fallbackPackageUrl -o $tmp',
    '      Write-Host ("$ npm install -g " + $tmp)',
    '      & $npm.Source install -g $tmp',
    '      $installSucceeded = $true',
    '      Remove-Item $tmp -ErrorAction SilentlyContinue',
    '    }',
    '  }',
    '}',
    '',
    'if (-not $installSucceeded) {',
    '  throw "OpenClaw installation failed across all paths."',
    '}',
    '$openclaw = Get-Command openclaw -ErrorAction SilentlyContinue',
    'if ($openclaw) {',
    '  Write-Host ("$ " + $openclaw.Source + " gateway install")',
    '  & $openclaw.Source gateway install *> $null',
    '  Write-Host ("$ " + $openclaw.Source + " gateway restart")',
    '  & $openclaw.Source gateway restart *> $null',
    '} else {',
    `  Write-Host "${messageNotOnPath}"`,
    '  exit 1',
    '}',
  ].join('\n')
}
