import { bashEnsureNodeAndNpmSnippet, bashRuntimeProbePrelude } from '@/lib/bash'

export type StarOfficeLabAction = 'install' | 'start' | 'stop' | 'restart'

const STAR_OFFICE_REPO_URL = 'https://github.com/ringhyacinth/Star-Office-UI.git'
const STAR_OFFICE_DEFAULT_BRANCH = 'main'
const STAR_OFFICE_DEFAULT_PORT = 18791
const STAR_OFFICE_DEFAULT_HEALTH_URL = `http://127.0.0.1:${STAR_OFFICE_DEFAULT_PORT}/health`

function quoteBashSingle(value: string) {
  return `'${value.replace(/'/g, `'"'"'`)}'`
}

function quotePowerShellSingle(value: string) {
  return `'${value.replace(/'/g, "''")}'`
}

export function buildStarOfficeLabScriptUnix(action: StarOfficeLabAction) {
  const prelude = bashRuntimeProbePrelude()
  const ensureNode = bashEnsureNodeAndNpmSnippet()
  const repoUrl = quoteBashSingle(STAR_OFFICE_REPO_URL)
  const branch = quoteBashSingle(STAR_OFFICE_DEFAULT_BRANCH)
  const healthUrl = quoteBashSingle(STAR_OFFICE_DEFAULT_HEALTH_URL)

  return [
    'set -euo pipefail',
    'log() { echo "[star-office-lab] $*"; }',
    'fail() { echo "[star-office-lab] ERROR: $*" >&2; exit 1; }',
    `action=${quoteBashSingle(action)}`,
    `repo_url=${repoUrl}`,
    `branch=${branch}`,
    'resolved_branch=""',
    `health_url=${healthUrl}`,
    'install_dir="$HOME/.holycrab/labs/star-office-ui"',
    'pid_file="$install_dir/.holycrab-star-office.pid"',
    'port_file="$install_dir/.holycrab-star-office.port"',
    'log_file="$install_dir/.holycrab-star-office.log"',
    'backend_dir="$install_dir/backend"',
    'venv_dir="$install_dir/.venv"',
    'venv_python="$venv_dir/bin/python"',
    '',
    'wait_health() {',
    '  local attempts="${1:-30}"',
    '  local delay="${2:-1}"',
    '  local i=0',
    '  while [ "$i" -lt "$attempts" ]; do',
    '    if curl -fsS "$health_url" >/dev/null 2>&1; then',
    '      return 0',
    '    fi',
    '    i=$((i + 1))',
    '    sleep "$delay"',
    '  done',
    '  return 1',
    '}',
    '',
    'pid_is_alive() {',
    '  local pid="$1"',
    '  [ -n "$pid" ] || return 1',
    '  kill -0 "$pid" >/dev/null 2>&1',
    '}',
    '',
    'port_in_use() {',
    '  local target="$1"',
    '  if command -v lsof >/dev/null 2>&1; then',
    '    lsof -nP -iTCP:"$target" -sTCP:LISTEN >/dev/null 2>&1',
    '    return $?',
    '  fi',
    '  if command -v nc >/dev/null 2>&1; then',
    '    nc -z 127.0.0.1 "$target" >/dev/null 2>&1',
    '    return $?',
    '  fi',
    '  return 1',
    '}',
    '',
    'pick_available_port() {',
    '  local start_port="${1:-18791}"',
    '  local p="$start_port"',
    '  while [ "$p" -lt $((start_port + 40)) ]; do',
    '    if ! port_in_use "$p"; then',
    '      echo "$p"',
    '      return 0',
    '    fi',
    '    p=$((p + 1))',
    '  done',
    '  return 1',
    '}',
    '',
    'configure_health_url_from_port_file() {',
    '  local selected=""',
    '  if [ -f "$port_file" ]; then',
    '    selected="$(cat "$port_file" 2>/dev/null | tr -d "\\r\\n " || true)"',
    '  fi',
    '  case "$selected" in',
    '    ""|*[!0-9]*) selected="" ;;',
    '  esac',
    '  if [ -z "$selected" ]; then',
    `    selected="${STAR_OFFICE_DEFAULT_PORT}"`,
    '  fi',
    '  health_url="http://127.0.0.1:${selected}/health"',
    '}',
    '',
    'ensure_python3() {',
    '  if command -v python3 >/dev/null 2>&1; then',
    '    return 0',
    '  fi',
    '  local os_name',
    '  os_name="$(uname -s 2>/dev/null || echo unknown)"',
    '  if [ "$os_name" = "Darwin" ]; then',
    '    if command -v brew >/dev/null 2>&1; then',
    '      log "python3 not found, installing via Homebrew..."',
    '      HOMEBREW_NO_AUTO_UPDATE=1 brew install python',
    '    else',
    '      fail "python3 not found and Homebrew is unavailable. Please install Python 3 manually."',
    '    fi',
    '  elif [ "$os_name" = "Linux" ]; then',
    '    if command -v apt-get >/dev/null 2>&1; then',
    '      if command -v sudo >/dev/null 2>&1; then',
    '        log "python3 not found, installing via apt..."',
    '        sudo apt-get update -y',
    '        sudo apt-get install -y python3 python3-pip python3-venv',
    '      elif [ "$(id -u)" = "0" ]; then',
    '        log "python3 not found, installing via apt (root)..."',
    '        apt-get update -y',
    '        apt-get install -y python3 python3-pip python3-venv',
    '      else',
    '        fail "python3 not found and apt needs sudo/root. Please install Python 3 manually."',
    '      fi',
    '    elif command -v dnf >/dev/null 2>&1; then',
    '      if command -v sudo >/dev/null 2>&1; then',
    '        sudo dnf install -y python3 python3-pip',
    '      elif [ "$(id -u)" = "0" ]; then',
    '        dnf install -y python3 python3-pip',
    '      else',
    '        fail "python3 not found and dnf needs sudo/root. Please install Python 3 manually."',
    '      fi',
    '    else',
    '      fail "python3 not found on Linux and no supported package manager detected."',
    '    fi',
    '  else',
    '    fail "python3 not found on unsupported OS (${os_name})."',
    '  fi',
    '  command -v python3 >/dev/null 2>&1 || fail "python3 still unavailable after installation."',
    '}',
    '',
    'ensure_pip() {',
    '  python3 -m pip --version >/dev/null 2>&1 || python3 -m ensurepip --upgrade >/dev/null 2>&1 || true',
    '  python3 -m pip --version >/dev/null 2>&1 || fail "pip unavailable for python3."',
    '  python3 -m pip install --upgrade pip setuptools wheel >/dev/null 2>&1 || true',
    '}',
    '',
    'ensure_pnpm() {',
    '  if command -v pnpm >/dev/null 2>&1; then',
    '    return 0',
    '  fi',
    '  log "pnpm not found, installing globally with npm..."',
    '  npm install -g pnpm >/dev/null 2>&1 || fail "failed to install pnpm via npm."',
    '  command -v pnpm >/dev/null 2>&1 || fail "pnpm still unavailable after installation."',
    '}',
    '',
    'prepare_repo() {',
    '  branch_exists_remote() {',
    '    local candidate="$1"',
    '    [ -n "$candidate" ] || return 1',
    '    local heads',
    '    heads="$(git ls-remote --heads "$repo_url" "$candidate" 2>/dev/null || true)"',
    '    [ -n "$heads" ]',
    '  }',
    '  if [ -z "$resolved_branch" ]; then',
    '    head_ref="$(git ls-remote --symref "$repo_url" HEAD 2>/dev/null | sed -n \'s#^ref: refs/heads/\\([^[:space:]]\\+\\)[[:space:]].*$#\\1#p\' | head -n1 || true)"',
    '    if [ -n "$head_ref" ]; then',
      '      resolved_branch="$head_ref"',
    '    elif branch_exists_remote "$branch"; then',
      '      resolved_branch="$branch"',
    '    elif branch_exists_remote "master"; then',
      '      resolved_branch="master"',
    '    elif branch_exists_remote "main"; then',
      '      resolved_branch="main"',
    '    else',
    '      fail "unable to resolve remote branch for ${repo_url}"',
    '    fi',
    '    log "Using remote branch: ${resolved_branch}"',
    '  fi',
    '  mkdir -p "$HOME/.holycrab/labs"',
    '  if [ -d "$install_dir/.git" ]; then',
    '    log "Updating Star Office UI repository..."',
    '    git -C "$install_dir" fetch --all --prune >/dev/null 2>&1 || true',
    '    git -C "$install_dir" checkout "$resolved_branch" >/dev/null 2>&1 || true',
    '    git -C "$install_dir" pull --ff-only || true',
    '  elif [ -d "$install_dir" ]; then',
    '    log "Install directory exists but is not a git repo. Replacing..."',
    '    rm -rf "$install_dir"',
    '    git clone --depth 1 --branch "$resolved_branch" "$repo_url" "$install_dir"',
    '  else',
    '    log "Cloning Star Office UI..."',
    '    git clone --depth 1 --branch "$resolved_branch" "$repo_url" "$install_dir"',
    '  fi',
    '}',
    '',
    'install_dependencies() {',
    '  [ -f "$install_dir/backend/requirements.txt" ] || fail "backend/requirements.txt missing."',
    '  if [ ! -x "$venv_python" ]; then',
    '    log "Creating Python virtualenv..."',
    '    python3 -m venv "$venv_dir"',
    '  fi',
    '  "$venv_python" -m pip install --upgrade pip setuptools wheel >/dev/null 2>&1 || true',
    '  "$venv_python" -m pip install -r "$install_dir/backend/requirements.txt"',
    '  [ -f "$install_dir/state.json" ] || cp "$install_dir/state.sample.json" "$install_dir/state.json"',
    '}',
    '',
    'stop_server() {',
    '  if [ -f "$pid_file" ]; then',
    '    pid="$(cat "$pid_file" 2>/dev/null || true)"',
    '    if pid_is_alive "$pid"; then',
    '      log "Stopping Star Office UI (pid=${pid})..."',
    '      kill "$pid" >/dev/null 2>&1 || true',
    '      for _ in 1 2 3 4 5 6 7 8 9 10; do',
    '        pid_is_alive "$pid" || break',
    '        sleep 0.4',
    '      done',
    '      pid_is_alive "$pid" && kill -9 "$pid" >/dev/null 2>&1 || true',
    '    fi',
    '    rm -f "$pid_file"',
    '  fi',
    '  pkill -f "$install_dir/backend/app.py" >/dev/null 2>&1 || true',
    '}',
    '',
    'start_server() {',
    '  [ -d "$backend_dir" ] || fail "backend directory missing. Please run install first."',
    '  [ -x "$venv_python" ] || fail "virtualenv python missing. Please run install first."',
    '  configure_health_url_from_port_file',
    '  if [ -f "$pid_file" ]; then',
    '    pid="$(cat "$pid_file" 2>/dev/null || true)"',
    '    if pid_is_alive "$pid" && wait_health 2 1; then',
    '      log "Star Office UI already running (pid=${pid})."',
    '      return 0',
    '    fi',
    '    rm -f "$pid_file"',
    '  fi',
    '  pkill -f "$install_dir/backend/app.py" >/dev/null 2>&1 || true',
    '  mkdir -p "$install_dir"',
    '  : > "$log_file"',
    `  selected_port="$(pick_available_port ${STAR_OFFICE_DEFAULT_PORT} || true)"`,
    '  [ -n "$selected_port" ] || fail "unable to find available local port for Star Office UI."',
    '  selected_gemini_api_key="${HOLYCRAB_STAR_OFFICE_GEMINI_API_KEY:-}"',
    '  selected_gemini_model="${HOLYCRAB_STAR_OFFICE_GEMINI_MODEL:-nanobanana-pro}"',
    '  selected_asset_drawer_pass="${HOLYCRAB_STAR_OFFICE_ASSET_DRAWER_PASS:-1234}"',
    '  health_url="http://127.0.0.1:${selected_port}/health"',
    '  printf "%s" "$selected_port" > "$port_file"',
    '  log "Starting Star Office UI on ${health_url}..."',
    '  (cd "$backend_dir" && GEMINI_API_KEY="$selected_gemini_api_key" GEMINI_MODEL="$selected_gemini_model" ASSET_DRAWER_PASS="$selected_asset_drawer_pass" STAR_OFFICE_PORT="$selected_port" nohup "$venv_python" -c \'import os, app as star_office_app; star_office_app.app.run(host="0.0.0.0", port=int(os.environ.get("STAR_OFFICE_PORT", "18791")), debug=False)\' >>"$log_file" 2>&1 & echo $! > "$pid_file")',
    '  wait_health 35 1 || fail "Star Office UI failed to become healthy. See ${log_file}."',
    '  log "Star Office UI is running."',
    '}',
    '',
    'log "Preparing runtime environment..."',
    prelude,
    'if ! command -v git >/dev/null 2>&1; then fail "git is required but unavailable."; fi',
    'if ! command -v curl >/dev/null 2>&1; then fail "curl is required but unavailable."; fi',
    'ensure_python3',
    'ensure_pip',
    ensureNode,
    'ensure_pnpm',
    'log "Environment summary:"',
    'echo "python3: $(python3 --version 2>/dev/null || echo missing)"',
    'echo "node: $(node -v 2>/dev/null || echo missing)"',
    'echo "npm: $(npm -v 2>/dev/null || echo missing)"',
    'echo "pnpm: $(pnpm -v 2>/dev/null || echo missing)"',
    '',
    'case "$action" in',
    '  install)',
    '    prepare_repo',
    '    install_dependencies',
    '    start_server',
    '    ;;',
    '  start)',
    '    start_server',
    '    ;;',
    '  stop)',
    '    stop_server',
    '    log "Stopped."',
    '    ;;',
    '  restart)',
    '    stop_server',
    '    start_server',
    '    ;;',
    '  *)',
    '    fail "unsupported action: $action"',
    '    ;;',
    'esac',
  ].join('\n')
}

export function buildStarOfficeLabScriptWindows(action: StarOfficeLabAction) {
  const repoUrl = STAR_OFFICE_REPO_URL.replace(/"/g, '""')
  const branch = STAR_OFFICE_DEFAULT_BRANCH.replace(/"/g, '""')
  const healthUrl = STAR_OFFICE_DEFAULT_HEALTH_URL.replace(/"/g, '""')

  return [
    '$ErrorActionPreference = "Stop"',
    '$action = ' + quotePowerShellSingle(action),
    `$repoUrl = "${repoUrl}"`,
    `$branch = "${branch}"`,
    '$resolvedBranch = ""',
    `$healthUrl = "${healthUrl}"`,
    '$installDir = Join-Path $HOME ".holycrab/labs/star-office-ui"',
    '$pidFile = Join-Path $installDir ".holycrab-star-office.pid"',
    '$logFile = Join-Path $installDir ".holycrab-star-office.log"',
    '$backendDir = Join-Path $installDir "backend"',
    '$venvDir = Join-Path $installDir ".venv"',
    '$venvPython = Join-Path $venvDir "Scripts\\python.exe"',
    '',
    'function Log-Step([string]$Message) { Write-Host ("[star-office-lab] " + $Message) }',
    'function Fail-Step([string]$Message) { throw ("[star-office-lab] " + $Message) }',
    '',
    'function Ensure-Command([string]$name) {',
    '  $cmd = Get-Command $name -ErrorAction SilentlyContinue',
    '  return $cmd',
    '}',
    '',
    'function Ensure-Python {',
    '  if (Ensure-Command "python") { return }',
    '  if (Ensure-Command "python3") { return }',
    '  $winget = Ensure-Command "winget"',
    '  if (-not $winget) { Fail-Step "python not found and winget unavailable." }',
    '  Log-Step "Installing Python via winget..."',
    '  & $winget.Source install --id Python.Python.3.12 -e --accept-package-agreements --accept-source-agreements',
    '}',
    '',
    'function Ensure-NodeNpmPnpm {',
    '  $node = Ensure-Command "node"',
    '  $npm = Ensure-Command "npm"',
    '  if (-not $node -or -not $npm) {',
    '    $winget = Ensure-Command "winget"',
    '    if (-not $winget) { Fail-Step "node/npm missing and winget unavailable." }',
    '    Log-Step "Installing Node.js via winget..."',
    '    & $winget.Source install --id OpenJS.NodeJS.LTS -e --accept-package-agreements --accept-source-agreements',
    '  }',
    '  if (-not (Ensure-Command "pnpm")) {',
    '    Log-Step "Installing pnpm via npm..."',
    '    npm install -g pnpm',
    '  }',
    '}',
    '',
    'function Wait-Health {',
    '  param([int]$Attempts = 35)',
    '  for ($i = 0; $i -lt $Attempts; $i++) {',
    '    try {',
    '      $resp = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing -TimeoutSec 2',
    '      if ($resp.StatusCode -ge 200 -and $resp.StatusCode -lt 500) { return $true }',
    '    } catch {}',
    '    Start-Sleep -Seconds 1',
    '  }',
    '  return $false',
    '}',
    '',
    'function Prepare-Repo {',
    '  if ([string]::IsNullOrWhiteSpace($resolvedBranch)) {',
    '    $headRef = ""',
    '    try {',
    '      $symref = git ls-remote --symref $repoUrl HEAD 2>$null',
    '      $first = $symref | Select-Object -First 1',
    '      if ($first -match "refs/heads/([^\\s]+)") {',
    '        $headRef = $Matches[1]',
    '      }',
    '    } catch {}',
    '    if (-not [string]::IsNullOrWhiteSpace($headRef)) {',
    '      $resolvedBranch = $headRef',
    '    } else {',
    '      $candidates = @($branch, "master", "main") | Select-Object -Unique',
    '      foreach ($candidate in $candidates) {',
    '        if ([string]::IsNullOrWhiteSpace($candidate)) { continue }',
    '        try {',
    '          $heads = git ls-remote --heads $repoUrl $candidate 2>$null',
    '          if ($heads) { $resolvedBranch = $candidate; break }',
    '        } catch {}',
    '      }',
    '    }',
    '    if ([string]::IsNullOrWhiteSpace($resolvedBranch)) {',
    '      Fail-Step ("unable to resolve remote branch for " + $repoUrl)',
    '    }',
    '    Log-Step ("Using remote branch: " + $resolvedBranch)',
    '  }',
    '  New-Item -Path (Join-Path $HOME ".holycrab/labs") -ItemType Directory -Force *> $null',
    '  if (Test-Path (Join-Path $installDir ".git")) {',
    '    Log-Step "Updating Star Office UI repository..."',
    '    git -C $installDir fetch --all --prune',
    '    git -C $installDir checkout $resolvedBranch',
    '    git -C $installDir pull --ff-only',
    '  } elseif (Test-Path $installDir) {',
    '    Remove-Item -Path $installDir -Recurse -Force',
    '    git clone --depth 1 --branch $resolvedBranch $repoUrl $installDir',
    '  } else {',
    '    git clone --depth 1 --branch $resolvedBranch $repoUrl $installDir',
    '  }',
    '}',
    '',
    'function Install-Deps {',
    '  $python = (Ensure-Command "python3"); if (-not $python) { $python = Ensure-Command "python" }',
    '  if (-not $python) { Fail-Step "Python unavailable." }',
    '  if (-not (Test-Path $venvPython)) {',
    '    & $python.Source -m venv $venvDir',
    '  }',
    '  & $venvPython -m pip install --upgrade pip setuptools wheel',
    '  & $venvPython -m pip install -r (Join-Path $installDir "backend/requirements.txt")',
    '  if (Test-Path (Join-Path $installDir "state.sample.json")) {',
    '    $stateFile = Join-Path $installDir "state.json"',
    '    if (-not (Test-Path $stateFile)) { Copy-Item (Join-Path $installDir "state.sample.json") $stateFile }',
    '  }',
    '}',
    '',
    'function Stop-Service {',
    '  if (Test-Path $pidFile) {',
    '    $pid = Get-Content $pidFile -ErrorAction SilentlyContinue',
    '    if ($pid) { Stop-Process -Id ([int]$pid) -Force -ErrorAction SilentlyContinue }',
    '    Remove-Item $pidFile -Force -ErrorAction SilentlyContinue',
    '  }',
    "  Get-CimInstance Win32_Process -Filter \"name = ''python.exe'' OR name = ''python3.exe''\" |",
    '    Where-Object { $_.CommandLine -like "*star-office-ui*backend\\app.py*" } |',
    '    ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }',
    '}',
    '',
    'function Start-Service {',
    '  if (-not (Test-Path $backendDir)) { Fail-Step "backend directory missing." }',
    '  if (-not (Test-Path $venvPython)) { Fail-Step "virtualenv python missing. Please run install first." }',
    '  if ((Test-Path $pidFile) -and (Wait-Health -Attempts 2)) { return }',
    '  if ($env:HOLYCRAB_STAR_OFFICE_GEMINI_API_KEY) { $env:GEMINI_API_KEY = $env:HOLYCRAB_STAR_OFFICE_GEMINI_API_KEY } else { Remove-Item Env:GEMINI_API_KEY -ErrorAction SilentlyContinue }',
    '  if ($env:HOLYCRAB_STAR_OFFICE_GEMINI_MODEL) { $env:GEMINI_MODEL = $env:HOLYCRAB_STAR_OFFICE_GEMINI_MODEL } elseif (-not $env:GEMINI_MODEL) { $env:GEMINI_MODEL = "nanobanana-pro" }',
    '  if ($env:HOLYCRAB_STAR_OFFICE_ASSET_DRAWER_PASS) { $env:ASSET_DRAWER_PASS = $env:HOLYCRAB_STAR_OFFICE_ASSET_DRAWER_PASS } elseif (-not $env:ASSET_DRAWER_PASS) { $env:ASSET_DRAWER_PASS = "1234" }',
    '  New-Item -Path $installDir -ItemType Directory -Force *> $null',
    '  $proc = Start-Process -FilePath $venvPython -ArgumentList "app.py" -WorkingDirectory $backendDir -PassThru -WindowStyle Hidden',
    '  $proc.Id | Set-Content -Path $pidFile -Encoding utf8',
    '  if (-not (Wait-Health -Attempts 35)) {',
    '    Stop-Process -Id $proc.Id -Force -ErrorAction SilentlyContinue',
    '    Fail-Step "Star Office UI failed to become healthy."',
    '  }',
    '}',
    '',
    'if (-not (Ensure-Command "git")) { Fail-Step "git is required." }',
    'Ensure-Python',
    'Ensure-NodeNpmPnpm',
    'Log-Step ("python: " + ((Ensure-Command "python3")?.Source ?? (Ensure-Command "python")?.Source ?? "missing"))',
    'Log-Step ("node: " + ((Ensure-Command "node")?.Source ?? "missing"))',
    'Log-Step ("npm: " + ((Ensure-Command "npm")?.Source ?? "missing"))',
    'Log-Step ("pnpm: " + ((Ensure-Command "pnpm")?.Source ?? "missing"))',
    '',
    'switch ($action) {',
    '  "install" { Prepare-Repo; Install-Deps; Start-Service }',
    '  "start" { Start-Service }',
    '  "stop" { Stop-Service }',
    '  "restart" { Stop-Service; Start-Service }',
    '  default { Fail-Step ("Unsupported action: " + $action) }',
    '}',
    'Log-Step "Done."',
  ].join('\n')
}

export function starOfficeLabUiUrl(port = STAR_OFFICE_DEFAULT_PORT) {
  return `http://127.0.0.1:${port}`
}
